- react.json
Add missing plugin `import`.
When extending `eslint-config` I get an error that eslint can't find the rule `import/dynamic-import-chunkname`.
@bigcommerce/frontend
> fix(common): add missing plugin import

- lerna.json
- packages/eslint-config/package.json
- packages/eslint-plugin/package.json
- Add version number to release commit
- Make `eslint-plugin` first version `0.1.0` so when we do a `premajor` we get `1.0.0-alpha.0` and not `2.0.0...`
> chore(common): prepare for prerelease

- packages/eslint-config/test/__snapshots__/typescript-eslint.spec.js.snap
- packages/eslint-config/test/eslint-serializer.js
- packages/eslint-config/test/eslint.spec.js
- packages/eslint-config/test/typescript-eslint.spec.js
test(config): use ESLint instead of deprecated CLIEngine
test(config): add stability tests for @typescript-eslint/all
> Refactor usage of CLIEngine and @typescript-eslint/all tests

- lerna.json
- packages/eslint-config/CHANGELOG.md
- packages/eslint-plugin/CHANGELOG.md
Since the changelogs were done pre-monorepo, they got messed up on first release. Re-generated them and we should be good moving forward.
> chore(common): re-generate changelogs

- packages/eslint-config/configs/react.js
- packages/eslint-config/test/__snapshots__/eslint.spec.js.snap
Update rules
`jsx-a11y/anchor-is-valid`: There is now some [documentation](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md#case-i-use-nextjs-and-im-getting-this-error-inside-of-links) on workarounds for Next.
`react/jsx-indent-props`: Not really needed because of prettier.
> feat(config): enable anchor-is-valid and remove jsx-ident-props

- packages/eslint-config/configs/base.js
- packages/eslint-config/package.json
- packages/eslint-config/test/__snapshots__/eslint.spec.js.snap
- yarn.lock
**feat(config): disallow getters and setters**
Missed this one when porting the config over.
**fix(config): switch case fallthrough no longer requires a linebreak**
We had a bug where the following will require a linebreak between the following pass-through cases:
```js
switch(name) {
case 'daniel':
case 'dan': {
}
}
```
Tried fixing it only with `adding-line-between-statements` by setting the config to something like:
```js
{
blankLine: 'never',
next: ['case'],
prev: ['case'],
},
{
blankLine: 'always',
next: ['case'],
prev: ['block-like'],
},
```
But that didn't work for multi-line non-blocks `cases`, had to add a plugin.
> Disallow getters/setters + switch case fallthrough fix

- packages/eslint-config/README.md
- packages/eslint-config/configs/base.js
- packages/eslint-config/configs/jest.js
- packages/eslint-config/configs/prettier.js
- packages/eslint-config/configs/react.js
- packages/eslint-config/configs/typescript.js
- packages/eslint-config/test/__snapshots__/eslint.spec.js.snap
Changed stylistic rules from `error` -> `warn`. We think this will give a better developer experience:
Error = Pay attention to this, you may need to change something.
Warn = Stylistic change, probably will be auto-fixed.
> feat(config): stylistic rules are now warnings

- packages/eslint-config/configs/react.js
- packages/eslint-config/configs/typescript.js
- packages/eslint-config/test/__snapshots__/eslint.spec.js.snap
We have a `react/` rule in our eslint-ts config. @chanceaclark found about this bug on a non-react ts repo. Since we don't load the react plugin it crashed.
> fix(config): move jsx-file-extension rule to react config

- packages/eslint-config/configs/react.js
- packages/eslint-config/test/__snapshots__/eslint.spec.js.snap
This rule has been deprecated and removed from the `recommended` rules on https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/pull/757.
More context on: https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/issues/398
Left a comment to remove it once it gets released.
> fix(config): disable jsx-a11y/no-onchange

- packages/eslint-config/configs/typescript.js
- packages/eslint-config/test/__snapshots__/eslint.spec.js.snap
Enable `@typescript-eslint/no-unnecessary-condition` to avoid unnecessary checks
It might also hint when types are not defined correctly. It will point out we are trying to check for something to exist, which might indicate the type is not reflecting the fact that it might not be defined.
https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-unnecessary-condition.md
> Enable @typescript-eslint/no-unnecessary-condition

- packages/eslint-config/configs/react.js
- packages/eslint-config/test/__snapshots__/eslint.spec.js.snap
This rule is not recommended by the react team and in a lot of cases might have performance issues.
> feat(config): allow arrow functions react/jsx-no-bind

- .circleci/config.yml
Run the tests once a week with no lockfile. We remove to lock file since this is what our consumers will be getting.
CI will fail when new rules are introduced / modified.
> chore(ci): FE-00 schedule test job

- packages/eslint-config/configs/react.js
- packages/eslint-config/test/__snapshots__/eslint.spec.js.snap
Forgot to loosen up this rule a little bit. We have this rule with the same config in a couple of repos. Restricting `'` and `"` is a bit too much IMO.
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-unescaped-entities.md
> feat(config): FE-00 unescaped entities denylist

- packages/eslint-config/package.json
Our config used to be a `.json` then we changed it to `.js` and forgot to update it here. Luckily, node defaults to `index.js` so it didn't break, however, the default is being deprecated.
> fix(config): FE-00 incorrect entrypoint

- packages/eslint-config/configs/typescript.js
- packages/eslint-config/test/__snapshots__/eslint.spec.js.snap
Currently, we enforce a the [default-case](https://eslint.org/docs/rules/default-case) rule for switches. Basically it enforces all switches to have a `default` case.
This rule makes sense when working with `js` as there is no way to make sure all cases are being handled, it is "safer" to have an explicit default.
However, in TS we have [@typescript-eslint/switch-exhaustiveness-check](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/switch-exhaustiveness-check.md#switch-exhaustiveness-check) which is enabled in our config.
Let's take a look at the following example:
```ts
type Animal = 'cat' | 'dog';
const sayHi = (animal: Animal): string => {
switch(animal) {
case 'cat':
return 'Purr Purr';
case 'dog':
return 'Woof woof';
default:
return …
```
> feat(config): FE-00 disable default-case for ts files

- packages/eslint-config/configs/prettier.js
- packages/eslint-config/test/__snapshots__/eslint.spec.js.snap
Enables the [`curly`](https://eslint.org/docs/rules/curly) rule. This is opinionated, but I'd like for us to keep consistency when writing conditionals/loops. It encourages "encapsulation" of logic and readability within blocks of code, rather than "being clever" with a one-liner.
We originally had this rule before we added Prettier. Prettier [disables this rule](https://github.com/prettier/eslint-config-prettier/blob/ab47f025c03b3091dce6dca0f3d785b11c7ec3ed/index.js#L10) so we need to add this back in via [their instructions](https://github.com/prettier/eslint-config-prettier#curly).
For instance,
```ts
if (something) {
doSomething();
}
```
is more readable than
```ts
if (something) doSomething();
```
> feat(config): FE-00 add curly rule

- packages/eslint-config/configs/typescript.js
- packages/eslint-config/test/__snapshots__/eslint.spec.js.snap
- packages/eslint-plugin/package.json
A recent change in the `no-misused-promises` rule made it fail when we
pass a function returning a promise into a prop that expects a void
return. This removes the check and relies on TS to make sure promises
are handled correctly.
```ts
const clicked = async () => {};
return <Component onClick={clicked} />
```
It won't allow promises in methods that are explicitly typed as void:
```diff
-const method = (): void => fetch();
+const method = (): void => {
+  void fetch();
+}
```
> fix(config): Allow functions returning promises to be passed into jsx attributes that expect void return

- packages/eslint-config/index.js
Don't add `jest` rules if `jest` is not present. This is currently failing for non-jest projects.
```
ESLint: 8.15.0
Error: Error while loading rule 'jest/no-deprecated-functions':
Unable to detect Jest version -
please ensure jest package is installed, or otherwise set version explicitly
```
> fix(config): FE-00 don't add jest rules if jest is not installed

- packages/eslint-config/configs/base.js
- packages/eslint-config/test/__snapshots__/d.ts.spec.js.snap
- packages/eslint-config/test/__snapshots__/js.spec.js.snap
- packages/eslint-config/test/__snapshots__/jsx.spec.js.snap
- packages/eslint-config/test/__snapshots__/spec.spec.js.snap
- packages/eslint-config/test/__snapshots__/ts.spec.js.snap
- packages/eslint-config/test/__snapshots__/tsx.spec.js.snap
- yarn.lock
We tend to mark as warnings things that'll get autofixed by eslint,
`func-names` doesn't have an autofix and must be fixed before saving.
<table>
<tr>
<td>Before
<td>After
<tr>
<td><img width="523" alt="image" src="https://user-images.githubusercontent.com/4542735/174933687-bb21baf1-1f1a-48db-8528-2644153e1315.png">
<td><img width="502" alt="image" src="https://user-images.githubusercontent.com/4542735/174933480-bc1a162b-7602-4818-935e-af338698051f.png">
</table>
> fix(config): FE-00 Mark `func-names` rule as error

- .circleci/config.yml
- packages/eslint-config/package.json
- yarn.lock
Was getting some issues resolving a package using `typesVersions` in their `package.json` (see https://github.com/import-js/eslint-import-resolver-typescript/issues/107). This was giving a false report that some modules were unresolved (via `import/no-unresolved). Bumping the import resolver fixes this.
N/A
> chore(config): FE-00 bump eslint-import-resolver-typescript

- package.json
- packages/eslint-config/configs/typescript.js
- packages/eslint-config/package.json
- packages/eslint-config/test/__snapshots__/d.ts.spec.js.snap
- packages/eslint-config/test/__snapshots__/ts.spec.js.snap
- packages/eslint-config/test/__snapshots__/tsx.spec.js.snap
- packages/eslint-config/test/__snapshots__/typescript-eslint.spec.js.snap
- packages/eslint-plugin/package.json
- yarn.lock
Support the latest TS@5 version. Includes a few new rules (see below comments).
Ran inside `@bigcommerce/big-design` (only TS issues):
> chore(common): FE-00 support typescript v5

- packages/eslint-config/configs/base.js
- packages/eslint-config/test/__snapshots__/d.ts.spec.js.snap
- packages/eslint-config/test/__snapshots__/js.spec.js.snap
- packages/eslint-config/test/__snapshots__/jsx.spec.js.snap
- packages/eslint-config/test/__snapshots__/spec.spec.js.snap
- packages/eslint-config/test/__snapshots__/ts.spec.js.snap
- packages/eslint-config/test/__snapshots__/tsx.spec.js.snap
Updates the `ecmaVersion` to `latest` in order to use the latest JS features. There are some modern features, like `import.meta` that can't be used with older `ecmaVersion` values. This enables features like that and more.
Tested with Catalyst and works as expected:
> feat: update ecmaVersion to latest

- package.json
- packages/eslint-config/configs/base.js
- packages/eslint-config/configs/jest.js
- packages/eslint-config/configs/typescript.js
- packages/eslint-config/jest.config.js
- packages/eslint-config/package.json
- packages/eslint-config/test/__fixtures__/tsconfig.json
- packages/eslint-config/test/__snapshots__/d.ts.spec.js.snap
- packages/eslint-config/test/__snapshots__/js.spec.js.snap
- packages/eslint-config/test/__snapshots__/jsx.spec.js.snap
- packages/eslint-config/test/__snapshots__/spec.spec.js.snap
- packages/eslint-config/test/__snapshots__/ts.spec.js.snap
- packages/eslint-config/test/__snapshots__/tsx.spec.js.snap
- packages/eslint-config/test/__snapshots__/typescript-eslint.spec.js.snap
- packages/eslint-config/test/d.ts.spec.js
- packages/eslint-config/test/getEslint.js
- packages/eslint-config/test/js.spec.js
- packages/eslint-config/test/jsx.spec.js
- packages/eslint-config/test/spec.spec.js
- packages/eslint-config/test/ts.spec.js
- packages/eslint-config/test/tsx.spec.js
- packages/eslint-plugin/package.json
- packages/eslint-plugin/rules/jsx-short-circuit-conditionals.js
- yarn.lock
Update all dependencies.
Prettier 3 is not supported by jest 29
@typescript-eslint does not support eslint 9
> chore: Update all dependencies

- .github/dependabot.yml
Prettier 3.x is incompatible with Jest 29, this causes issues on any repo trying to use it and also having Jest 29 installed.
We can unpin it when Jest 30 is released.
> chore: Pin prettier/eslint-plugin-prettier

- packages/eslint-config/test/d.ts.spec.js
- packages/eslint-config/test/js.spec.js
- packages/eslint-config/test/jsx.spec.js
- packages/eslint-config/test/spec.spec.js
- packages/eslint-config/test/ts.spec.js
- packages/eslint-config/test/tsx.spec.js
Adds a test to check if there are any deprecated rules outstanding.
Will fix the deprecations in the next PR:
- https://github.com/bigcommerce/eslint-config/pull/202
n/a
> test: add check for deprecated rules

- package.json
> fix: change remote to origin

- packages/eslint-plugin/package.json
The config relies on [version 7.8.0 of `@typescript-eslint/parser`](https://github.com/bigcommerce/eslint-config/blob/master/packages/eslint-config/package.json#L27), which means this peer dependency is out of sync with what the config wants. This updates the version to the same version as the config.
> fix(plugin): update peer dependency

- packages/eslint-config/test/__snapshots__/d.ts.spec.js.snap
- packages/eslint-config/test/__snapshots__/js.spec.js.snap
- packages/eslint-config/test/__snapshots__/jsx.spec.js.snap
- packages/eslint-config/test/__snapshots__/spec.spec.js.snap
- packages/eslint-config/test/__snapshots__/ts.spec.js.snap
- packages/eslint-config/test/__snapshots__/tsx.spec.js.snap
- packages/eslint-config/test/__snapshots__/typescript-eslint.spec.js.snap
- yarn.lock
Updates the dep to latest pinned version using `yarn upgrade-interactive`.
N/A
> chore(deps): update deps using yarn upgrade-interactive

- packages/eslint-config/test/__snapshots__/d.ts.spec.js.snap
- packages/eslint-config/test/__snapshots__/ts.spec.js.snap
- packages/eslint-config/test/__snapshots__/tsx.spec.js.snap
- packages/eslint-config/test/__snapshots__/typescript-eslint.spec.js.snap
- yarn.lock
Updates the dependencies to the latest version. This also enables us to use the latest typescript version without any issues.
> chore(deps): update deps to latest minor versions

- package.json
- packages/eslint-config/package.json
- packages/eslint-plugin/package.json
This PR adds eslint to peerDependencies with the version range >=8.14.0 <10, while still keeping it in devDependencies.
This enables consuming projects to upgrade to ESLint 9, without breaking this package’s local development or linting setup.
N/A
ping @animesh1987 @icatalina
> QPT-796 Allow repos using eslint-config to upgrade eslint to 9 or above
